
package com.Interface;

import com.data.SalesInvoiceHeader;
import com.data.SalesInvoiceLine;
import com.data.LeftInvoiceTableModel;
import com.process.SalesInvoiceListener;
import com.process.RowSelectorListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTable;


public class SalesInvoiceWindow extends javax.swing.JFrame {

    /**
     * Creates new form InvoiceWindow
     */
    public SalesInvoiceWindow() {
        initComponents();
    }

    /**
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        InvoicesTable = new javax.swing.JTable();
        CreateNewInvoiceButton = new javax.swing.JButton();
        DeleteInvoiceButton = new javax.swing.JButton();
        InvoiceNumberLabel = new javax.swing.JLabel();
        InvoiceDateLabel = new javax.swing.JLabel();
        CustomerNameLabel = new javax.swing.JLabel();
        InvoiceTotalLabel = new javax.swing.JLabel();
        InvoiceNumberLabelField = new javax.swing.JLabel();
        InvoiceDateLabelField = new javax.swing.JLabel();
        CustomerNameLabelField = new javax.swing.JLabel();
        InvoiceTotalLabelField = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ItemsTable = new javax.swing.JTable();
        SaveInvoiceItemButton = new javax.swing.JButton();
        CancelInvoiceItemButton = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        LoadFileMenuItem = new javax.swing.JMenuItem();
        SaveFileMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InvoicesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        InvoicesTable.getSelectionModel().addListSelectionListener(rowSelectedListener);
        jScrollPane1.setViewportView(InvoicesTable);

        CreateNewInvoiceButton.setText("Create New Invoice");
        CreateNewInvoiceButton.addActionListener(actionListener);

        DeleteInvoiceButton.setText("Delete Invoice");
        DeleteInvoiceButton.addActionListener(actionListener);

        InvoiceNumberLabel.setText("Invoice Number");

        InvoiceDateLabel.setText("Invoice Date");

        CustomerNameLabel.setText("Customer Name");

        InvoiceTotalLabel.setText("Invoice Total");

        ItemsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(ItemsTable);

        SaveInvoiceItemButton.setText("Add Item");
        SaveInvoiceItemButton.setToolTipText("");
        SaveInvoiceItemButton.addActionListener(actionListener);

        CancelInvoiceItemButton.setText("Delete Item");
        CancelInvoiceItemButton.addActionListener(actionListener);

        FileMenu.setText("File");

        LoadFileMenuItem.setText("Load File");
        LoadFileMenuItem.addActionListener(actionListener);
        FileMenu.add(LoadFileMenuItem);

        SaveFileMenuItem.setText("Save File");
        SaveFileMenuItem.addActionListener(actionListener);
        FileMenu.add(SaveFileMenuItem);

        MenuBar.add(FileMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(InvoiceNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(InvoiceDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CustomerNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(InvoiceTotalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InvoiceNumberLabelField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(InvoiceDateLabelField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CustomerNameLabelField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(InvoiceTotalLabelField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(6, 6, 6))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(CreateNewInvoiceButton)
                .addGap(100, 100, 100)
                .addComponent(DeleteInvoiceButton)
                .addGap(167, 167, 167)
                .addComponent(SaveInvoiceItemButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CancelInvoiceItemButton)
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InvoiceNumberLabel)
                            .addComponent(InvoiceNumberLabelField))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InvoiceDateLabel)
                            .addComponent(InvoiceDateLabelField))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CustomerNameLabel)
                            .addComponent(CustomerNameLabelField))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InvoiceTotalLabel)
                            .addComponent(InvoiceTotalLabelField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CreateNewInvoiceButton)
                    .addComponent(DeleteInvoiceButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SaveInvoiceItemButton)
                        .addComponent(CancelInvoiceItemButton)))
                .addGap(0, 27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesInvoiceWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesInvoiceWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesInvoiceWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesInvoiceWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesInvoiceWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelInvoiceItemButton;
    private javax.swing.JButton CreateNewInvoiceButton;
    private javax.swing.JLabel CustomerNameLabel;
    private javax.swing.JLabel CustomerNameLabelField;
    private javax.swing.JButton DeleteInvoiceButton;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JLabel InvoiceDateLabel;
    private javax.swing.JLabel InvoiceDateLabelField;
    private javax.swing.JLabel InvoiceNumberLabel;
    private javax.swing.JLabel InvoiceNumberLabelField;
    private javax.swing.JLabel InvoiceTotalLabel;
    private javax.swing.JLabel InvoiceTotalLabelField;
    private javax.swing.JTable InvoicesTable;
    private javax.swing.JTable ItemsTable;
    private javax.swing.JMenuItem LoadFileMenuItem;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem SaveFileMenuItem;
    private javax.swing.JButton SaveInvoiceItemButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

private SalesInvoiceListener actionListener = new SalesInvoiceListener(this);
private ArrayList<SalesInvoiceHeader> invoicesArray;
private ArrayList<SalesInvoiceLine> invoiceLinesArray;
private LeftInvoiceTableModel leftTableModel;
public static SimpleDateFormat shortDateFormat = new SimpleDateFormat("dd-MM-yyyy");
private RowSelectorListener rowSelectedListener = new RowSelectorListener(this);



    public void setInvoiceLinesArray(ArrayList<SalesInvoiceLine> invoiceLinesArray) {
        this.invoiceLinesArray = invoiceLinesArray;
    }

    public void setInvoicesArray(ArrayList<SalesInvoiceHeader> invoicesArray) {
        this.invoicesArray = invoicesArray;
    }
    public ArrayList<SalesInvoiceLine> getInvoiceLinesArray() {
        return invoiceLinesArray;
    }
    public ArrayList<SalesInvoiceHeader> getInvoicesArray() {
        return invoicesArray;
    }

    
    public SalesInvoiceHeader getInvoiceObject(int invoiceID)
    {
        for (SalesInvoiceHeader invoice : invoicesArray){
            if (invoice.getInvoiceNumber() == invoiceID){
                return invoice;
            }
        }
        return null;
    }

    public LeftInvoiceTableModel getLeftTableModel() {
        return leftTableModel;
    }

    public void setLeftTableModel(LeftInvoiceTableModel leftTableModel) {
        this.leftTableModel = leftTableModel;
    }

    public JTable getleftInvoicesTable() {
        return InvoicesTable;
    }

    public JTable getItemsTable() {
        return ItemsTable;
    }

    public JLabel getCustomerNameLabelField() {
        return CustomerNameLabelField;
    }

    public JLabel getInvoiceDateLabelField() {
        return InvoiceDateLabelField;
    }

    public JLabel getInvoiceNumberLabelField() {
        return InvoiceNumberLabelField;
    }

    public JLabel getInvoiceTotalLabelField() {
        return InvoiceTotalLabelField;
    }

    public SalesInvoiceListener getActionListener() {
        return actionListener;
    }

}
